# --- TICKERS DATABASE ---

FOREX = [
    'EURUSD=X', 'GBPUSD=X', 'USDJPY=X', 'AUDUSD=X', 'USDCAD=X', 'USDCHF=X', 'NZDUSD=X',
    'EURJPY=X', 'GBPJPY=X', 'EURGBP=X', 'AUDJPY=X', 'EURAUD=X', 'EURCAD=X', 'AUDNZD=X',
    'GBPAUD=X', 'GBPCAD=X', 'CHFJPY=X', 'CADJPY=X', 'NZDJPY=X'
]

CRYPTO = [
    'BTC-USD', 'ETH-USD', 'SOL-USD', 'BNB-USD', 'XRP-USD', 'ADA-USD', 'DOGE-USD', 
    'AVAX-USD', 'TRX-USD', 'DOT-USD', 'LINK-USD', 'MATIC-USD', 'LTC-USD', 'UNI-USD'
]

# Top 100 NSE (Nifty 100)
INDIA = [
    'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'INFY.NS', 'BHARTIARTL.NS', 'SBIN.NS', 
    'LICI.NS', 'ITC.NS', 'HINDUNILVR.NS', 'LT.NS', 'BAJFINANCE.NS', 'HCLTECH.NS', 'KOTAKBANK.NS', 
    'AXISBANK.NS', 'ADANIENT.NS', 'SUNPHARMA.NS', 'TITAN.NS', 'MARUTI.NS', 'ULTRACEMCO.NS', 
    'ASIANPAINT.NS', 'NTPC.NS', 'TATAMOTORS.NS', 'POWERGRID.NS', 'ADANIPORTS.NS', 'COALINDIA.NS', 
    'BAJAJFINSV.NS', 'TATASTEEL.NS', 'ONGC.NS', 'ADANIPOWER.NS', 'JSWSTEEL.NS', 'M&M.NS', 
    'INDIGO.NS', 'SIEMENS.NS', 'HAL.NS', 'SBILIFE.NS', 'GRASIM.NS', 'HINDALCO.NS', 'BRITANNIA.NS', 
    'NESTLEIND.NS', 'VBL.NS', 'DLF.NS', 'IOC.NS', 'ZOMATO.NS', 'TRENT.NS', 'CIPLA.NS', 'GAIL.NS', 
    'BPCL.NS', 'ABB.NS', 'BEL.NS', 'BAJAJ-AUTO.NS', 'TATACONSUM.NS', 'SHREECEM.NS', 'TECHM.NS', 
    'DRREDDY.NS', 'HDFCLIFE.NS', 'WIPRO.NS', 'JIOFIN.NS', 'HEROMOTOCO.NS', 'DIVISLAB.NS', 
    'EICHERMOT.NS', 'LTIM.NS', 'APOLLOHOSP.NS', 'AMBUJACEM.NS', 'INDUSINDBK.NS', 'ADANIGREEN.NS', 
    'ADANITRANS.NS', 'UNITDSPR.NS', 'PIIND.NS', 'POLYCAB.NS', 'SRF.NS', 'IRCTC.NS', 'MOTHERSON.NS', 
    'BOSCHLTD.NS', 'PIDILITIND.NS', 'CANBK.NS', 'TVSMOTOR.NS', 'CHOLAFIN.NS', 'GODREJCP.NS', 
    'PNB.NS', 'BANKBARODA.NS', 'BERGEPAINT.NS', 'AUFILER.NS', 'IDFCFIRSTB.NS', 'YESBANK.NS', 
    'TATACOMM.NS', 'HAVELLS.NS', 'CUMMINSIND.NS', 'MAXHEALTH.NS', 'ABBOTINDIA.NS', 'PFC.NS', 
    'RECLTD.NS', 'CONCOR.NS', 'COLPAL.NS', 'DALBHARAT.NS', 'PETRONET.NS', 'NMDC.NS', 'OBEROIRLTY.NS'
]

# Top 100 S&P 500 (By Market Cap)
US_STOCKS = [
    'AAPL', 'MSFT', 'GOOGL', 'AMZN', 'NVDA', 'META', 'TSLA', 'BRK-B', 'AVGO', 'UNH', 'V', 'JPM', 
    'LLY', 'XOM', 'MA', 'JNJ', 'PG', 'HD', 'ADBE', 'ASML', 'COST', 'ORCL', 'CVX', 'MRK', 'KO', 
    'ABBV', 'CRM', 'PEP', 'BAC', 'NFLX', 'AMD', 'TMO', 'WMT', 'ACN', 'MCD', 'CSCO', 'LIN', 'INTU', 
    'ABT', 'DIS', 'PFE', 'INTC', 'CMCSA', 'VZ', 'TXN', 'DHR', 'AMAT', 'PM', 'QCOM', 'CAT', 'NKE', 
    'AXP', 'UNP', 'LOW', 'ISRG', 'IBM', 'SPGI', 'COP', 'SYK', 'GE', 'HON', 'AMGN', 'RTX', 'T', 
    'LMT', 'PLD', 'ELV', 'DE', 'NOW', 'GS', 'BLK', 'MDLZ', 'BA', 'TJX', 'MMC', 'ADI', 'ADP', 
    'LRCX', 'ZTS', 'AMT', 'CI', 'C', 'BMY', 'VRTX', 'REGN', 'GILD', 'SCHW', 'MU', 'PANW', 
    'CB', 'SNPS', 'CDNS', 'TGT', 'KLAC', 'EQIX', 'MDT', 'MO', 'BSX', 'PGR', 'EOG'
]
