# --- TICKERS DATABASE ---

FOREX = ['EURUSD=X', 'GBPUSD=X', 'USDJPY=X', 'AUDUSD=X', 'USDCAD=X', 'USDCHF=X', 'NZDUSD=X', 'EURJPY=X', 'GBPJPY=X']

CRYPTO = ['BTC-USD', 'ETH-USD', 'SOL-USD', 'BNB-USD', 'XRP-USD', 'ADA-USD', 'DOGE-USD', 'AVAX-USD', 'LINK-USD', 'DOT-USD']

# TOP 250 INDIAN STOCKS (Nifty 200 + Top Midcaps)
INDIA = [
    'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'INFY.NS', 'BHARTIARTL.NS', 'SBIN.NS', 'LICI.NS', 'ITC.NS', 'HINDUNILVR.NS',
    'LT.NS', 'BAJFINANCE.NS', 'HCLTECH.NS', 'KOTAKBANK.NS', 'AXISBANK.NS', 'ADANIENT.NS', 'SUNPHARMA.NS', 'TITAN.NS', 'MARUTI.NS', 'ULTRACEMCO.NS',
    'ASIANPAINT.NS', 'NTPC.NS', 'TATAMOTORS.NS', 'POWERGRID.NS', 'ADANIPORTS.NS', 'COALINDIA.NS', 'BAJAJFINSV.NS', 'TATASTEEL.NS', 'ONGC.NS', 'ADANIPOWER.NS',
    'JSWSTEEL.NS', 'M&M.NS', 'INDIGO.NS', 'SIEMENS.NS', 'HAL.NS', 'SBILIFE.NS', 'GRASIM.NS', 'HINDALCO.NS', 'BRITANNIA.NS', 'NESTLEIND.NS',
    'VBL.NS', 'DLF.NS', 'IOC.NS', 'ZOMATO.NS', 'TRENT.NS', 'CIPLA.NS', 'GAIL.NS', 'BPCL.NS', 'ABB.NS', 'BEL.NS',
    'BAJAJ-AUTO.NS', 'TATACONSUM.NS', 'SHREECEM.NS', 'TECHM.NS', 'DRREDDY.NS', 'HDFCLIFE.NS', 'WIPRO.NS', 'JIOFIN.NS', 'HEROMOTOCO.NS', 'DIVISLAB.NS',
    'EICHERMOT.NS', 'LTIM.NS', 'APOLLOHOSP.NS', 'AMBUJACEM.NS', 'INDUSINDBK.NS', 'ADANIGREEN.NS', 'ATGL.NS', 'UNITDSPR.NS', 'PIIND.NS', 'POLYCAB.NS',
    'SRF.NS', 'IRCTC.NS', 'MOTHERSON.NS', 'BOSCHLTD.NS', 'PIDILITIND.NS', 'CANBK.NS', 'TVSMOTOR.NS', 'CHOLAFIN.NS', 'GODREJCP.NS', 'PNB.NS',
    'BANKBARODA.NS', 'BERGEPAINT.NS', 'AUFILER.NS', 'IDFCFIRSTB.NS', 'YESBANK.NS', 'TATACOMM.NS', 'HAVELLS.NS', 'CUMMINSIND.NS', 'MAXHEALTH.NS', 'ABBOTINDIA.NS',
    'PFC.NS', 'RECLTD.NS', 'CONCOR.NS', 'COLPAL.NS', 'DALBHARAT.NS', 'PETRONET.NS', 'NMDC.NS', 'OBEROIRLTY.NS', 'RVNL.NS', 'IRFC.NS',
    'MAZDOCK.NS', 'DIXON.NS', 'TATAELXSI.NS', 'KPITTECH.NS', 'COFORGE.NS', 'PERSISTENT.NS', 'SUZLON.NS', 'JSL.NS', 'GLENMARK.NS', 'LUPIN.NS',
    'AUROPHARMA.NS', 'BIOCON.NS', 'ASHOKLEY.NS', 'BALKRISIND.NS', 'MRF.NS', 'TATACHEM.NS', 'DEEPAKNTR.NS', 'KEI.NS', 'HDFCAMC.NS', 'MCX.NS',
    'IEX.NS', 'PHOENIXLTD.NS', 'PRESTIGE.NS', 'NYKAA.NS', 'PAYTM.NS', 'POLICYBZR.NS', 'DATAPATTNS.NS', 'MAHABANK.NS', 'CENTRALBK.NS', 'IOB.NS',
    'UCOBANK.NS', 'HUDCO.NS', 'IRB.NS', 'NHPC.NS', 'SJVN.NS', 'NBCC.NS', 'BHEL.NS', 'UNIONBANK.NS', 'IDBI.NS', 'INDIANB.NS',
    'GICRE.NS', 'NIACL.NS', 'OIL.NS', 'FACT.NS', 'MAHSEAMLESS.NS', 'APLLTD.NS', 'BSOFT.NS', 'CYIENT.NS', 'ZENSARTECH.NS', 'SONACOMS.NS',
    'KAYNES.NS', 'AETHER.NS', 'CLEAN.NS', 'LINDEINDIA.NS', 'SOLARINDS.NS', 'GUJGASLTD.NS', 'IGL.NS', 'MGL.NS', 'AIAENG.NS', 'FLUOROCHEM.NS',
    'ESCORTS.NS', 'AMARAJABAT.NS', 'EXIDEIND.NS', 'RADICO.NS', 'KALYANKJIL.NS', 'GRINFRA.NS', 'KNRCON.NS', 'PNCINFRA.NS', 'NCC.NS', 'ITDC.NS',
    'SWSOLAR.NS', 'GMRINFRA.NS', 'JINDALWORLD.NS', 'WELCORP.NS', 'RATNAMANI.NS', 'HINDZINC.NS', 'HINDCOPPER.NS', 'NATIONALUM.NS', 'SAIL.NS', 'NMDC.NS',
    'KIOCL.NS', 'GPPL.NS', 'GESHIP.NS', 'SCI.NS', 'RITES.NS', 'RVNL.NS', 'TITAGARH.NS', 'BEML.NS', 'MAHLOG.NS', 'DELHIVERY.NS',
    'BLS.NS', 'EASEMYTRIP.NS', 'AFFLE.NS', 'TANLA.NS', 'ROUTE.NS', 'NAZARA.NS', 'JUSTDIAL.NS', 'TIINDIA.NS', 'CARBORUNIV.NS', 'TIMKEN.NS',
    'SKFINDIA.NS', 'CUMMINSIND.NS', 'HONAUT.NS', 'THERMAX.NS', 'TRITURBINE.NS', 'ELGIEQUIP.NS', 'BDL.NS', 'HAL.NS', 'DATA PATTERNS.NS', 'IDEA.NS'
]

# TOP 250 US STOCKS (S&P 100 + Nasdaq 100 + Top Russell 1000)
US_STOCKS = [
    'AAPL', 'MSFT', 'GOOGL', 'AMZN', 'NVDA', 'META', 'TSLA', 'BRK-B', 'AVGO', 'UNH', 'V', 'JPM', 'LLY', 'XOM', 'MA', 'JNJ', 'PG', 'HD', 'ADBE', 'ASML',
    'COST', 'ORCL', 'CVX', 'MRK', 'KO', 'ABBV', 'CRM', 'PEP', 'BAC', 'NFLX', 'AMD', 'TMO', 'WMT', 'ACN', 'MCD', 'CSCO', 'LIN', 'INTU', 'ABT', 'DIS',
    'PFE', 'INTC', 'CMCSA', 'VZ', 'TXN', 'DHR', 'AMAT', 'PM', 'QCOM', 'CAT', 'NKE', 'AXP', 'UNP', 'LOW', 'ISRG', 'IBM', 'SPGI', 'COP', 'SYK', 'GE',
    'HON', 'AMGN', 'RTX', 'T', 'LMT', 'PLD', 'ELV', 'DE', 'NOW', 'GS', 'BLK', 'MDLZ', 'BA', 'TJX', 'MMC', 'ADI', 'ADP', 'LRCX', 'ZTS', 'AMT',
    'CI', 'C', 'BMY', 'VRTX', 'REGN', 'GILD', 'SCHW', 'MU', 'PANW', 'CB', 'SNPS', 'CDNS', 'TGT', 'KLAC', 'EQIX', 'MDT', 'MO', 'BSX', 'PGR', 'EOG',
    'ETN', 'ITW', 'WM', 'ICE', 'MCK', 'SHW', 'CSX', 'MAR', 'ORLY', 'MCO', 'PH', 'SLB', 'VRT', 'DELL', 'ANET', 'CRWD', 'MSTR', 'SMCI', 'PLTR', 'SNOW',
    'WDAY', 'TEAM', 'ADSK', 'DDOG', 'ZS', 'OKTA', 'MDB', 'TTD', 'NET', 'PANW', 'FTNT', 'FSLR', 'ENPH', 'SQ', 'PYPL', 'SHOP', 'UBER', 'ABNB', 'DASH', 'DKNG',
    'RIVN', 'LCID', 'COIN', 'HOOD', 'ROKU', 'U', 'RBLX', 'AFRM', 'PLUG', 'RUN', 'SOFI', 'MARA', 'RIOT', 'CLSK', 'PATH', 'AI', 'GME', 'AMC', 'ARM', 'TSM',
    'SAP', 'TM', 'NVO', 'AZN', 'BABA', 'PDD', 'JD', 'BIDU', 'NTES', 'MELI', 'SE', 'CPNG', 'TME', 'LI', 'XPEV', 'NIO', 'F', 'GM', 'STLA', 'HMC',
    'UBER', 'LYFT', 'DAL', 'UAL', 'AAL', 'LUV', 'FEDEX', 'UPS', 'CAT', 'DE', 'DELL', 'HPQ', 'HPE', 'NTAP', 'STX', 'WDC', 'MU', 'AMD', 'INTC', 'NVDA',
    'AMAT', 'LRCX', 'KLAC', 'ASML', 'TXN', 'ADI', 'MCHP', 'ON', 'NXPI', 'STM', 'AVGO', 'QRVO', 'SWKS', 'CRUS', 'MPWR', 'LSCC', 'ALGM', 'DIOD', 'POWI', 'SYNA'
]
